accounts/urls.py
from django.urls import re_path

from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'sign_in/$', views.sign_in, name='sign_in'),
    re_path(r'sign_up/$', views.sign_up, name='sign_up'),
    re_path(r'sign_out/$', views.sign_out, name='sign_out'),
    re_path(r'profile/$', views.profile, name='profile'),
    re_path(r'profile/edit/$', views.edit_profile,
            name='edit_profile'),
    re_path(r'profile/change_avatar/$', views.edit_avatar,
            name='edit_avatar'),
    re_path(r'profile/change_avatar/rotate', views.rotate_image,
            name='rotate_image'),
    re_path(r'profile/change_avatar/crop', views.crop_image,
            name='crop_image'),
    re_path(r'profile/change_avatar/flip', views.flip_image,
            name='flip_image'),
    re_path(r'profile/change_password/$', views.edit_password,
            name='edit_password'),
]

project_7/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^tinymce/', include('tinymce.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from tinymce.models import HTMLField


# Profile model using Django's built-in user model
class Profile(models.Model):
    user = models.OneToOneField(User,
                                related_name='profile',
                                on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    bio = HTMLField(blank=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True)
    city = models.CharField(blank=True, max_length=100)
    country = CountryField(blank=True)
    hobby = models.CharField(max_length=100, blank=True)


# Signal methods to create and save profiles once User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import (UserCreationForm,
                                       UserChangeForm,
                                       PasswordChangeForm)
from django.core import validators
from django.utils.safestring import mark_safe
from django_countries.widgets import CountrySelectWidget

from PIL import Image
from tinymce.widgets import TinyMCE
from django.core.files import File
import re


from . import models


class SignUpForm(UserCreationForm):
    """Using django's built-in template for user sign up"""
    verify_email = forms.EmailField(label='Verify email', required=True)

    class Meta:
        model = models.User
        fields = [
            'username',
            'email',
            'verify_email',
            'password1',
            'password2'
        ]

    def cleaned(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('verify_email')

        if email != verify:
            raise forms.ValidationError(
                    'Try again. Make sure your emails match'
                )


class EditUserForm(forms.ModelForm):
    """Edit profile form, includes email verification, excludes password"""

    # Add fields not in Profile Model here
    verify_email = forms.EmailField(label='Please verify your email',
                                    required=True)

    class Meta:
        model = models.User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'verify_email',
        ]

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('verify_email')

        if email != verify:
            raise forms.ValidationError(
                'Try again. Make sure your emails match'
            )


class EditProfileForm(forms.ModelForm):
    birth_date = forms.DateField(
                            input_formats=['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y'],
                            required=False,
                            widget=forms.DateInput(attrs={'id': 'birth_date'})
                            )

    bio = forms.CharField(widget=TinyMCE(attrs={'rows': 80}),
                          required=False,
                          min_length=10)

    widgets = {'country': CountrySelectWidget()}

    class Meta:
        model = models.Profile
        fields = [
            'birth_date',
            'avatar',
            'country',
            'city',
            'hobby',
            'bio',
        ]


class EditPasswordForm(forms.Form):
    """Edit Password Form"""
    min_length = 14

    # create the fields required for password reset
    old_password = forms.CharField(widget=forms.PasswordInput(),
                                   label='Old Password')

    new_password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'data-indicator': 'pwindicator',
               'id': 'new_password',
               'id_for_label': 'new_password'}),
        label='New Password')

    new_password2 = forms.CharField(widget=forms.PasswordInput(),
                                    label='Confirm New Password')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(EditPasswordForm, self).__init__(*args, **kwargs)

        self.fields['new_password1'].help_text = mark_safe(
            '<ul>'
            '<li>Must not be the same as current password</li>\n'
            '<li>Minimum length 14 characters</li>\n'
            '<li>Must contain uppercase and lowercase letters</li>\n'
            '<li>Must include one or more numerical digits</li>\n'
            '<li>Must include one or more of special characters @ # $</li>\n'
            '<li>Cannot contain the username, first or last name</li>\n'
            '</ul>'
        )

    # Check for password additional validations in clean method
    def clean(self):
        cleaned_data = super(EditPasswordForm, self).clean()

        old_password = self.cleaned_data.get('old_password')
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        # check if old password is correct
        if not self.user.check_password(old_password):
            raise forms.ValidationError('Current Password Incorrect!')

        # Check new password not equal to current password
        if new_password1 == old_password:
            raise forms.ValidationError("New Password cannot"
                                        "be same as Old Password")

        # Check for minimum length
        if len(new_password1) < self.min_length:
            raise forms.ValidationError("Password must be at least"
                                        "{} characters".format(self.min_length)
                                        )

        # check for upper and lower case letters
        if (not re.search(r'([a-z])+', new_password1) or
                not re.search(r'[A-Z]+', new_password1)):
            raise forms.ValidationError("New password must contain "
                                        "Uppercase and Lowercase letters.")

        # check new password contains special characters
        if not re.search(r'\d+', new_password1):
            raise forms.ValidationError("The new password must include at "
                                        "least one number.")

        # check for special characters
        if not re.search(r'([@#$])+', new_password1):
            raise forms.ValidationError(
                "Password must contain one of the following @, #, $.")

        # check that password is not part of username or full name
        user_first = self.user.first_name.lower()
        user_last = self.user.last_name.lower()
        user_username = self.user.username.lower()

        # if user provided first and last name then run this validation
        # first_name and last_name are not required inputs
        if user_first or user_last:
            if (user_first in new_password1.lower() or
                    user_last in new_password1.lower() or
                    user_username in new_password1.lower()):
                raise forms.ValidationError(
                    "New password cannot contain "
                    "parts of your username or full name."
                                            )
        else:
            pass

        # check that password confirmation matches
        if new_password1 != new_password2:
            raise forms.ValidationError(
                "Passwords must match"
            )

        return cleaned_data


class EditAvatarForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('avatar',)


class EditCropForm(forms.Form):
    left = forms.CharField()
    top = forms.CharField()
    right = forms.CharField()
    bottom = forms.CharField()

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(EditCropForm, self).__init__(*args, **kwargs)

    def clean(self):
        with Image.open(self.user.profile.avatar.path) as image:
            width, height = image.size

            left = int(self.cleaned_data['left'])
            top = int(self.cleaned_data['top'])
            right = int(self.cleaned_data['right'])
            bottom = int(self.cleaned_data['bottom'])

            max_left = width - right
            max_top = height - bottom

            if (left >= max_left
                    or top >= max_top
                    or left >= width
                    or top >= height
                    or right > width
                    or bottom > height
                    or left < 0
                    or top < 0
                    or right <= 0
                    or bottom <= 0):
                raise forms.ValidationError("Cropping box is not valid.")

accounts/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.conf import settings

from PIL import Image
from . models import Profile
from . import forms


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('accounts:profile')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = forms.SignUpForm()
    if request.method == 'POST':
        form = forms.SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "Success! Account created. You are signed in."
            )
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def profile(request):
    """User profile view to display user details"""
    user = request.user
    return render(request, 'accounts/profile.html', {'user': user})


@login_required
def edit_profile(request):
    """Edit view for both User & Profile forms of user details"""

    if request.method == 'POST':
        user_form = forms.EditUserForm(request.POST, instance=request.user)
        profile_form = forms.EditProfileForm(request.POST, request.FILES,
                                             instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            print(settings.MEDIA_ROOT)
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile successfully updated!')
            return HttpResponseRedirect(reverse('accounts:profile'))
        else:
            messages.error(request, 'Please correct the error below')
    else:
        user_form = forms.EditUserForm(instance=request.user)
        profile_form = forms.EditProfileForm(instance=request.user.profile)
    return render(request, 'accounts/change_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


@login_required
def edit_password(request):
    """Edit view for password"""
    user = request.user
    form = forms.EditPasswordForm(user)
    if request.method == 'POST':
        form = forms.EditPasswordForm(data=request.POST, user=user)
        if form.is_valid():
            user.set_password(form.cleaned_data['new_password1'])
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request,
                             'Your password was successfully changed!')
            return HttpResponseRedirect(reverse('home'))

    return render(request, 'accounts/change_password.html', {'form': form})


@login_required
def edit_avatar(request):
    """Edit profile avatar"""

    form = forms.EditAvatarForm(instance=request.user.profile)
    if request.method == 'POST':
        form = forms.EditAvatarForm(request.POST,
                                    instance=request.user.profile,
                                    files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Avatar changes saved!")
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/change_avatar.html', {'form': form})


@login_required
def rotate_image(request):
    with Image.open(request.user.profile.avatar.path) as image:
        image = image.transpose(Image.ROTATE_270)
        image.save(request.user.profile.avatar.path)
    return HttpResponseRedirect(reverse('accounts:edit_avatar'))


@login_required
def flip_image(request):
    with Image.open(request.user.profile.avatar.path) as image:
        image = image.transpose(Image.FLIP_LEFT_RIGHT)
        image.save(request.user.profile.avatar.path)
    return HttpResponseRedirect(reverse('accounts:edit_avatar'))


@login_required
def crop_image(request):
    form = forms.EditCropForm(user=request.user)
    with Image.open(request.user.profile.avatar.path) as image:
        width, heigth = image.size
        size = str(width) + 'x' + str(heigth)
        if request.method == 'POST':
            form = forms.EditCropForm(user=request.user, data=request.POST)
            if form.is_valid():
                box = (int(form.cleaned_data['left']),
                       int(form.cleaned_data['top']),
                       int(form.cleaned_data['right']),
                       int(form.cleaned_data['bottom']),
                       )
                image = image.crop(box)
                image.save(request.user.profile.avatar.path)
                return HttpResponseRedirect(reverse('accounts:edit_avatar'))
        return render(request, 'accounts/change_avatar.html',
                      {'form': form, 'size': size})

accounts/templates/accounts/change_avatar.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} | {{ user.username }}{% endblock %}

{% block body %}
    <div class="grid-75">
        {% if user.profile.avatar %}
            <div>
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}" width="300px">
                <br/>
                <a href="{% url 'accounts:rotate_image' %}" class="button">Rotate</a>
                <a href="{% url 'accounts:crop_image' %}" class="button">Crop</a>
                <a href="{% url 'accounts:flip_image' %}" class="button">Flip</a>
            </div>
            <div>
                {% if size %}
                    <h3>Image size is {{ size }}</h3>
                {% endif %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Apply</button>
                </form>
            </div>
        {% else %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_ul }}
                <button type="submit">Save avatar</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/change_password.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} | Change Password | {{ user.username }}{% endblock %}

{% block js %}
<script type="text/javascript"
        src="{% static "accounts/js/jquery.pwstrength.js" %}"></script>
<script type="text/javascript">
    jQuery(function($) { $('#new_password').pwstrength(); });
</script>
{% endblock %}


{% block css %}
<link href={% static "accounts/css/style.css" %} rel="stylesheet" type="text/css">
{% endblock %}


{% block body %}
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <p>Password Indicator</p>
    <div id="pwindicator">
        <div class="bar"></div>
        <div class="label"></div>
    </div>
    <br/>

    <input type="submit" class="button-primary" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/change_profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} | Edit Profile {{ user.username }}{% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static "accounts/css/font_roboto/roboto.css" %}">
<link rel="stylesheet" href="{% static "accounts/css/dhtmlxcalendar.css" %}">
{% endblock %}


{% block js %}
 <!--Tinymce Text-Editor (Must be in Head Tag) -->
  <script src="{% static 'accounts/js/tinymce/tinymce.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'accounts/js/tinymce/custom.js' %}" ></script>

    <script type="text/javascript"
        src="{% static "accounts/js/dhtmlxcalendar.js" %}"></script>

 <!--Date of Birth Calendar -->
<script>
var myCalendar;
window.onload = function() {
    myCalendar = new dhtmlXCalendarObject(["birth_date"]);
};
</script>
{% endblock %}


{% block body %}

<form action='' method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" class="button-primary" value="Save Changes">
</form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} | {{ user.username }}{% endblock %}

{% block body %}
    <div class="grid-75">
    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" width="75">
    {% else %}
        <img src="{% static 'accounts/none/no_img.png' %}" width="75">
    {% endif %}
    <br>
        <div>Username: {{user.username}}</div>
        <div>Email: {{user.email}}</div>
        <div>First Name: {{user.first_name}}</div>
        <div>Last Name: {{user.last_name}}</div>
        <div>Date of Birth: {{user.profile.birth_date}}</div>
        <div>Hobby: {{user.profile.hobby}}</div>
        <div>City: {{user.profile.city}}</div>
        <div>Country: {{user.profile.country.name}}</div>
        <br>
        <div>Bio:<br>{{user.profile.bio|safe}}</div>
    </div>
    <br>

    <a href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
    <br/>
    <a href="{% url 'accounts:edit_avatar' %}">Edit Profile Image</a>
    <br/>
    <a href="{% url 'accounts:edit_password' %}">Change Password</a>


{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}