accounts/urls.py
from django.urls import re_path

from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'sign_in/$', views.sign_in, name='sign_in'),
    re_path(r'sign_up/$', views.sign_up, name='sign_up'),
    re_path(r'sign_out/$', views.sign_out, name='sign_out'),
    re_path(r'profile/$', views.profile, name='profile'),
    re_path(r'profile/edit/$', views.edit_profile,
            name='edit_profile'),
    re_path(r'profile/change_avatar/$', views.edit_avatar,
            name='edit_avatar'),
    re_path(r'profile/change_avatar/rotate', views.rotate_image,
            name='rotate_image'),
    re_path(r'profile/change_avatar/crop', views.crop_image,
            name='crop_image'),
    re_path(r'profile/change_avatar/flip', views.flip_image,
            name='flip_image'),
    re_path(r'profile/change_password/$', views.edit_password,
            name='edit_password'),
]

project_7/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^tinymce/', include('tinymce.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-75">
    {% if user.is_authenticated %}
        <h1>Welcome {{ user.username }}!</h1>
        {% else %}
        <h1>Welcome!</h1>
        {% endif %}
        <p>Let's get started and set up a profile.</p>
        <p>Sign up to set up a profile.</p>
        <p>If you already have a profile, sign in to view and edit your profile</p>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Django Profile{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}" type="text/css">
    {% block css %}{% endblock %}

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>
    {% block js %}{% endblock %}


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        <li><a href="#">nav</a></li>
                        <li><a href="#">here?</a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                            <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>